blank_issues_enabled: false
contact_links:
  - name: I Have A Question!
    url: https://github.com/Po2432/Po2432-s-BetterCraft/discussions/categories/q-a
    about: If you have a question ask it to community in GitHub discussions.
