name: Feature request
description: Suggest an idea or improvement for the project
title: "Feature Request: [Your Idea's Title]"
labels: 
  - type: suggestion
body:
  - type: textarea
    attributes:
      label: Problem Description
      description: Is your feature request related to a problem? Provide a clear and concise explanation of the issue.
      placeholder: ex. Users face difficulty navigating the interface in dark mode...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Solution Proposal
      description: Describe the solution or improvement you'd like to see implemented.
      placeholder: ex. Add customizable themes for better user experience.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Considered Alternatives
      description: Provide details on any alternative solutions you've explored or considered.
      placeholder: ex. I tried adjusting brightness settings manually, but it doesn't resolve the issue for dark mode.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Context
      description: Add any other information, screenshots, or context that could help explain your request.
      placeholder: ex. Attached is an image showing current interface limitations.
    validations:
      required: false
