name: Feature request
description: Suggest an idea or improvement for the project
title: "Feature Request: Your Idea's Title"
labels: "type: suggestion"
body:
  - type: textarea
    attributes:
      label: Is your feature request related to a problem?
      description: If it is, describe the problem you're having. If not, feel free to ignore.
      placeholder: ex. rubby would be good.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: ex. Add customizable themes for better user experience.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: What other options have you considered to obtain the change you want
      placeholder: ex. I tried adjusting brightness settings manually, but it doesn't resolve the issue for dark mode.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
      placeholder: ex. Attached is an image showing current interface limitations.
    validations:
      required: false
